### ISSUE TITLE
python2.[67] setup.py --version fails with TypeError: coercing to Unicode: need string or buffer, int found

### ISSUE THREAD

**Issue by normalex** [habnabit/vcversioner#6]
```
$ python setup.py --version
Traceback (most recent call last):
.....
  File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 232, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib64/python2.6/distutils/dist.py", line 451, in parse_command_line
    args = parser.getopt(args=self.script_args, object=self)
  File "/usr/lib64/python2.6/distutils/fancy_getopt.py", line 286, in getopt
    val = getattr(object, attr, 0) + 1
TypeError: coercing to Unicode: need string or buffer, int found
```
The issue is the current last line in vcversioner.py 
`dist.version = dist.metadata.version = find_version(**value).version`
it should just be 
`dist.metadata.version = find_version(**value).version`

Tested using python2.6 and 2.7

**Comment by habnabit** [comment]
Sorry about the late response here. Since you appear to have dug into this, can you explain (for posterity?) why this change is necessary?

**Comment by harlowja** [comment]
Just my 2 cents,

```$ python setup.py --version``` is a pretty basic and supposedly supported command. So it working would be great (vs not working). I personally sometimes use this, and packagers might use it, so having a known standard command working would be great.

**Comment by habnabit** [comment]
@harlowja I'm definitely not opposed to this fix; I just want to understand it. There was a reason I had to put the version in both places, but I don't remember what it was.

**Comment by nhuray** [comment]
@habnabit @harlowja Hi guys I got exactly the same issue. Can I help to fix it ?

**Comment by nhuray** [comment]
@habnabit I checked in ```distutils.dist```module and it seems there's no attribute ```version``` in the ```Distribution```class but there's one in ```DistributionMetadata```.  So that's why calling ```self.version``` on ```Distribution``` object fails.

Unfortunately, I don't know how I can link to the source code :(

**Comment by nhuray** [comment]
@habnabit Do you want I submit a pull request to fix this issue ?

**Comment by nhuray** [comment]
@harlowja @habnabit Hey guys how can we move forward with this issue ?

**Comment by nhuray** [comment]
Hey @habnabit could you answer my questions ?

**Comment by Julian** [comment]
I'm not sure where you're looking, maybe your distutils is different, but `Distribution` definitely *does* have such an attribute.

```
⊙  python -c 'from distutils.dist import Distribution; print Distribution().version'                julian@yoga
0
```

**Comment by normalex** [comment]
@Julian: the Distribution will get that attribute later in the execution, however in the context of where the vcversioner is plugged, the proper place is DistributionMetadata which is a wrapper over setup.py  kwargs metadata.

**Comment by Julian** [comment]
@normalex sounds good to me, are you advising @habnabit to apply the OP's suggested change then?

**Comment by dstufft** [comment]
``Distribution().version`` and ``DistributionMetadata().version`` are different things.

``Distribution().version`` is ``0`` if the ``--version`` flag was not used and is ``1`` if the ``--version`` flag was used. It's a boolean value that indicates the options that this is being executed with.

You just want to assign to ``DistributionMetadata().version``. Then ``Distribution().get_version()`` should return the correct version as well.
